import { Lesson } from "@/types";

export const LESSONS: Lesson[] = [
  {
    id: "alphabet",
    title: "ASL Alphabet",
    category: "Foundations",
    description: "Learn all 26 letters of the American Sign Language alphabet",
    difficulty: "beginner",
    xpReward: 100,
    estimatedTime: 20,
    thumbnail: "🔤",
    signs: [
      { id: "a", word: "A", description: "Fist with thumb on side", handShape: "A", movement: "Static", location: "Neutral space", animationFrames: [], exampleSentence: "A is for Apple" },
      { id: "b", word: "B", description: "Four fingers together, thumb folded in", handShape: "B", movement: "Static", location: "Neutral space", animationFrames: [], exampleSentence: "B is for Ball" },
      { id: "c", word: "C", description: "Curved hand like the letter C", handShape: "C", movement: "Static", location: "Neutral space", animationFrames: [], exampleSentence: "C is for Cat" },
    ],
  },
  {
    id: "numbers",
    title: "Numbers 1-20",
    category: "Foundations",
    description: "Count and express numbers in sign language",
    difficulty: "beginner",
    xpReward: 80,
    estimatedTime: 15,
    thumbnail: "🔢",
    signs: [
      { id: "1", word: "1", description: "Index finger pointing up", handShape: "1", movement: "Static", location: "Neutral space", animationFrames: [] },
      { id: "2", word: "2", description: "Index and middle fingers up", handShape: "2", movement: "Static", location: "Neutral space", animationFrames: [] },
      { id: "3", word: "3", description: "Thumb, index, middle fingers up", handShape: "3", movement: "Static", location: "Neutral space", animationFrames: [] },
    ],
  },
  {
    id: "greetings",
    title: "Greetings",
    category: "Daily Life",
    description: "Learn essential greeting signs",
    difficulty: "beginner",
    xpReward: 120,
    estimatedTime: 18,
    thumbnail: "👋",
    signs: [
      { id: "hello", word: "Hello", description: "Flat hand moving away from forehead", handShape: "B", movement: "Arc outward", location: "Forehead", animationFrames: [], exampleSentence: "Hello, nice to meet you!" },
      { id: "goodbye", word: "Goodbye", description: "Wave hand open and closed", handShape: "5", movement: "Wave", location: "Neutral space", animationFrames: [] },
      { id: "thank-you", word: "Thank You", description: "Flat hand from chin moving outward", handShape: "B", movement: "Forward arc", location: "Chin", animationFrames: [], exampleSentence: "Thank you for your help" },
      { id: "please", word: "Please", description: "Circular motion on chest", handShape: "B", movement: "Circular", location: "Chest", animationFrames: [] },
      { id: "sorry", word: "Sorry", description: "Fist circling on chest", handShape: "A", movement: "Circular", location: "Chest", animationFrames: [] },
      { id: "welcome", word: "Welcome", description: "Open hand sweeping inward", handShape: "B", movement: "Inward sweep", location: "Side", animationFrames: [] },
    ],
  },
  {
    id: "family",
    title: "Family Members",
    category: "Daily Life",
    description: "Signs for family relationships",
    difficulty: "beginner",
    xpReward: 100,
    estimatedTime: 20,
    thumbnail: "👨‍👩‍👧‍👦",
    signs: [
      { id: "mother", word: "Mother", description: "Thumb touches chin", handShape: "5", movement: "Tap", location: "Chin", animationFrames: [] },
      { id: "father", word: "Father", description: "Thumb touches forehead", handShape: "5", movement: "Tap", location: "Forehead", animationFrames: [] },
      { id: "sister", word: "Sister", description: "A-hand from jaw downward", handShape: "A", movement: "Downward", location: "Jaw to chest", animationFrames: [] },
      { id: "brother", word: "Brother", description: "L-hand from forehead downward", handShape: "L", movement: "Downward", location: "Forehead to chest", animationFrames: [] },
    ],
  },
  {
    id: "food",
    title: "Food & Drinks",
    category: "Daily Life",
    description: "Common food and drink vocabulary",
    difficulty: "beginner",
    xpReward: 110,
    estimatedTime: 22,
    thumbnail: "🍎",
    signs: [
      { id: "eat", word: "Eat", description: "Fingers to mouth", handShape: "Flat O", movement: "Repeated tap to mouth", location: "Mouth", animationFrames: [] },
      { id: "drink", word: "Drink", description: "Curved hand tilted to mouth", handShape: "C", movement: "Tilt upward", location: "Mouth", animationFrames: [] },
      { id: "water", word: "Water", description: "W hand taps chin", handShape: "W", movement: "Tap", location: "Chin", animationFrames: [] },
      { id: "food", word: "Food", description: "Fingers touch mouth repeatedly", handShape: "Flat O", movement: "Repeated touch", location: "Mouth", animationFrames: [] },
    ],
  },
  {
    id: "emergency",
    title: "Emergency Signs",
    category: "Safety",
    description: "Critical signs for emergency situations",
    difficulty: "beginner",
    xpReward: 150,
    estimatedTime: 15,
    thumbnail: "🚨",
    signs: [
      { id: "help", word: "Help", description: "Fist on flat palm, move upward", handShape: "A on B", movement: "Upward lift", location: "Neutral space", animationFrames: [], exampleSentence: "I need help!" },
      { id: "danger", word: "Danger", description: "A-hands, one brushes outward", handShape: "A", movement: "Brush outward", location: "Chest area", animationFrames: [] },
      { id: "hospital", word: "Hospital", description: "H-hand draws cross on arm", handShape: "H", movement: "Cross pattern", location: "Upper arm", animationFrames: [] },
      { id: "police", word: "Police", description: "C-hand taps shoulder", handShape: "C", movement: "Tap", location: "Shoulder", animationFrames: [] },
      { id: "fire", word: "Fire", description: "Wiggling fingers moving upward", handShape: "5", movement: "Upward wiggle", location: "Low to high", animationFrames: [] },
    ],
  },
  {
    id: "medical",
    title: "Medical",
    category: "Health",
    description: "Medical and health related signs",
    difficulty: "intermediate",
    xpReward: 130,
    estimatedTime: 25,
    thumbnail: "🏥",
    signs: [
      { id: "doctor", word: "Doctor", description: "D-hand taps wrist pulse point", handShape: "D", movement: "Tap", location: "Wrist", animationFrames: [] },
      { id: "medicine", word: "Medicine", description: "Middle finger circles on palm", handShape: "8", movement: "Circular", location: "Palm", animationFrames: [] },
      { id: "pain", word: "Pain", description: "Index fingers pointing toward each other", handShape: "1", movement: "Move toward each other", location: "Affected area", animationFrames: [] },
    ],
  },
  {
    id: "school",
    title: "School & Education",
    category: "Education",
    description: "Signs for school and learning",
    difficulty: "beginner",
    xpReward: 100,
    estimatedTime: 20,
    thumbnail: "🏫",
    signs: [
      { id: "learn", word: "Learn", description: "Flat hand to forehead, close fingers", handShape: "B to O", movement: "To forehead", location: "Forehead", animationFrames: [] },
      { id: "teacher", word: "Teacher", description: "Flat O hands from head outward", handShape: "Flat O", movement: "Forward", location: "Temples", animationFrames: [] },
      { id: "book", word: "Book", description: "Open flat hands like a book", handShape: "B", movement: "Open outward", location: "Neutral space", animationFrames: [] },
      { id: "write", word: "Write", description: "Pinched fingers on flat palm", handShape: "F", movement: "Writing motion", location: "Palm", animationFrames: [] },
    ],
  },
  {
    id: "office",
    title: "Office & Work",
    category: "Professional",
    description: "Professional and workplace signs",
    difficulty: "intermediate",
    xpReward: 120,
    estimatedTime: 22,
    thumbnail: "💼",
    signs: [
      { id: "work", word: "Work", description: "S-hands tap wrists together", handShape: "S", movement: "Tap down", location: "Wrists", animationFrames: [] },
      { id: "computer", word: "Computer", description: "C-hand on arm, move upward", handShape: "C", movement: "Upward slide", location: "Forearm", animationFrames: [] },
      { id: "meeting", word: "Meeting", description: "5-hands converge together", handShape: "5", movement: "Come together", location: "Neutral space", animationFrames: [] },
    ],
  },
  {
    id: "travel",
    title: "Travel & Places",
    category: "Travel",
    description: "Signs for travel and places",
    difficulty: "intermediate",
    xpReward: 110,
    estimatedTime: 20,
    thumbnail: "✈️",
    signs: [
      { id: "airplane", word: "Airplane", description: "Y-hand with index finger, move forward", handShape: "Y+I", movement: "Forward glide", location: "Neutral space", animationFrames: [] },
      { id: "hotel", word: "Hotel", description: "H-hand on back of other hand", handShape: "H", movement: "Rocking", location: "Back of hand", animationFrames: [] },
      { id: "map", word: "Map", description: "M-hand across flat palm", handShape: "M", movement: "Horizontal sweep", location: "Palm", animationFrames: [] },
    ],
  },
  {
    id: "daily-conversation",
    title: "Daily Conversation",
    category: "Communication",
    description: "Common phrases for everyday communication",
    difficulty: "intermediate",
    xpReward: 140,
    estimatedTime: 30,
    thumbnail: "💬",
    signs: [
      { id: "yes", word: "Yes", description: "S-hand nods like a head nod", handShape: "S", movement: "Nod down", location: "Neutral space", animationFrames: [] },
      { id: "no", word: "No", description: "Index and middle finger snap to thumb", handShape: "Open to closed", movement: "Snap", location: "Neutral space", animationFrames: [] },
      { id: "maybe", word: "Maybe", description: "Both flat hands alternate up and down", handShape: "B", movement: "Alternating up/down", location: "Neutral space", animationFrames: [] },
      { id: "understand", word: "Understand", description: "Index finger flicks up from fist at forehead", handShape: "S to 1", movement: "Flick up", location: "Forehead", animationFrames: [] },
    ],
  },
  {
    id: "advanced",
    title: "Advanced Communication",
    category: "Advanced",
    description: "Complex signs for fluent communication",
    difficulty: "advanced",
    xpReward: 200,
    estimatedTime: 40,
    thumbnail: "🎓",
    signs: [
      { id: "important", word: "Important", description: "F-hands rise from below to meet", handShape: "F", movement: "Rise upward", location: "Neutral space", animationFrames: [] },
      { id: "experience", word: "Experience", description: "Open hand sweeps from temple forward, closes", handShape: "5 to A", movement: "Forward close", location: "Temple", animationFrames: [] },
    ],
  },
];

export const CATEGORIES = [
  { id: "foundations", name: "Foundations", icon: "🏗️", color: "from-blue-500 to-cyan-500" },
  { id: "daily-life", name: "Daily Life", icon: "🏠", color: "from-green-500 to-emerald-500" },
  { id: "safety", name: "Safety", icon: "🛡️", color: "from-red-500 to-orange-500" },
  { id: "health", name: "Health", icon: "❤️", color: "from-pink-500 to-rose-500" },
  { id: "education", name: "Education", icon: "📚", color: "from-purple-500 to-violet-500" },
  { id: "professional", name: "Professional", icon: "💼", color: "from-slate-500 to-gray-500" },
  { id: "travel", name: "Travel", icon: "✈️", color: "from-sky-500 to-blue-500" },
  { id: "communication", name: "Communication", icon: "💬", color: "from-indigo-500 to-purple-500" },
  { id: "advanced", name: "Advanced", icon: "🎓", color: "from-amber-500 to-yellow-500" },
];

export const ACHIEVEMENTS = [
  { id: "first-lesson", title: "First Step", description: "Complete your first lesson", icon: "🎯", xpReward: 50, condition: "complete_lesson_1" },
  { id: "streak-3", title: "On a Roll", description: "Maintain a 3-day streak", icon: "🔥", xpReward: 100, condition: "streak_3" },
  { id: "streak-7", title: "Week Warrior", description: "Maintain a 7-day streak", icon: "⚡", xpReward: 200, condition: "streak_7" },
  { id: "alphabet-master", title: "Alphabet Master", description: "Complete the ASL Alphabet lesson", icon: "🔤", xpReward: 150, condition: "complete_alphabet" },
  { id: "quiz-ace", title: "Quiz Ace", description: "Score 100% on a quiz", icon: "🏆", xpReward: 200, condition: "quiz_perfect" },
  { id: "practice-100", title: "Dedicated Learner", description: "Complete 100 practice sessions", icon: "💪", xpReward: 300, condition: "practice_100" },
  { id: "level-5", title: "Rising Star", description: "Reach Level 5", icon: "⭐", xpReward: 250, condition: "level_5" },
  { id: "level-10", title: "Sign Language Hero", description: "Reach Level 10", icon: "🦸", xpReward: 500, condition: "level_10" },
  { id: "community-sharer", title: "Community Spirit", description: "Share your first achievement", icon: "🤝", xpReward: 75, condition: "share_achievement" },
  { id: "speed-demon", title: "Speed Demon", description: "Complete a timed challenge in under 60 seconds", icon: "⚡", xpReward: 175, condition: "speed_challenge" },
];

export const GESTURES_TO_RECOGNIZE = [
  "Hello", "Thank You", "Yes", "No", "Help", "Water", "Hospital", "Please", "Good Morning", "Welcome"
];
